# Generated by Django 5.2.4 on 2025-07-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0002_media_jeudeplateau_rename_name_membre_prenom_cd_dvd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeudeplateau',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
